name: ESP Watchdog

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check ThingSpeak
        run: |
          URL="https://api.thingspeak.com/channels/3369305/feeds.json?results=1"
          RESPONSE=$(curl -s "$URL")

          TIME=$(echo "$RESPONSE" | jq -r '.feeds[0].created_at')

          if [ -z "$TIME" ] || [ "$TIME" = "null" ]; then
            echo "NO_DATA"
            exit 0
          fi

          LAST=$(date -u -d "${TIME//T/ }" +%s)
          NOW=$(date -u +%s)
          DIFF=$((NOW - LAST))

          echo $DIFF > diff.txt

      - name: Send ntfy
        run: |
          DIFF=$(cat diff.txt)
          URL="${{ secrets.NTFY_URL }}"

          if [ "$DIFF" -gt 300 ]; then
            curl -d "🔴 ESP OFFLINE" "$URL"
          else
            curl -d "🟢 ESP ONLINE" "$URL"
          fi
