name: NTFY Alerts

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send ntfy alert
        run: |
          curl -d "🔴 ESP ALERT (Upptime detected issue)" "${{ secrets.NTFY_URL }}"
